export const ROSTER = [
  { id:'duwane', name:'DuWane Jonston', title:'The Foundation', style:'Power Wrestler', color:'#a92f37', accent:'#171717', skin:'#9a5c39', hair:'#17120f', speed:5, power:9, defense:8, reach:6, stamina:7, move:'People’s Quake', special:'A ground-shaking slam that launches a crimson shockwave.', look:{ hairStyle:'bald', beard:'goatee', width:1.16, height:1.03, gear:'wristbands', mark:'shoulder' } },
  { id:'jean', name:'Jean SeenEnough', title:'The Unseen Force', style:'Balanced Brawler', color:'#2d63d4', accent:'#e92738', skin:'#efbd91', hair:'#9b7b58', speed:7, power:8, defense:7, reach:6, stamina:8, move:'You Missed Me', special:'A vanishing shoulder charge with a delayed second impact.', look:{ hairStyle:'crew', beard:'none', width:1.08, height:1.04, gear:'bands', mark:'none' } },
  { id:'slater', name:'Slater Ibrahim', title:'The Lion of Legacy', style:'Long-Range Striker', color:'#b79a16', accent:'#172f59', skin:'#d39a72', hair:'#18120f', speed:7, power:8, defense:5, reach:10, stamina:9, move:'Lion’s Volley', special:'A spinning aerial kick with unmatched reach.', look:{ hairStyle:'manbun', beard:'goatee', width:.89, height:1.16, gear:'longsocks', mark:'none' } },
  { id:'aden', name:'Aden Zion', title:'The Last Stylist', style:'Precision Kickboxer', color:'#8b45c6', accent:'#16e1c1', skin:'#6d3c26', hair:'#16100e', speed:10, power:6, defense:6, reach:8, stamina:10, move:'Zion Shift', special:'A blur-step counter ending in a neon roundhouse.', look:{ hairStyle:'highfade', beard:'trim', width:.92, height:1.08, gear:'anklewraps', mark:'chest' } },
  { id:'antonio', name:'Antonio Joseph', title:'Royal Thunder', style:'Heavyweight Boxer', color:'#f4f4f0', accent:'#d5ac25', skin:'#603a28', hair:'#14110e', speed:6, power:10, defense:8, reach:7, stamina:8, move:'Crown Breaker', special:'A crushing three-punch combination finished by an uppercut.', look:{ hairStyle:'closecrop', beard:'trim', width:1.14, height:1.09, gear:'gloves', mark:'none' } },
  { id:'brass', name:'Brass Lee', title:'The Golden Dragon', style:'Martial Artist', color:'#f2c118', accent:'#171717', skin:'#d49a6a', hair:'#11100e', speed:10, power:6, defense:5, reach:6, stamina:10, move:'Dragon Echo', special:'A rapid chain of strikes too fast for the eye.', look:{ hairStyle:'sideswept', beard:'none', width:.82, height:1.02, gear:'headband', mark:'dragon' } },
  { id:'buck', name:'Woodchuck Buck', title:'The Final Fact', style:'Counter Fighter', color:'#5b3924', accent:'#b12822', skin:'#e0a97a', hair:'#b06e3c', speed:6, power:9, defense:9, reach:6, stamina:7, move:'Infinite Roundhouse', special:'A legendary counter-kick that stops any advance.', look:{ hairStyle:'flat', beard:'moustache', width:1.05, height:.98, gear:'belt', mark:'none' } },
  { id:'shake', name:'Shake A Take', title:'The Big Problem', style:'Super Heavyweight', color:'#5f297e', accent:'#f3d244', skin:'#553522', hair:'#111111', speed:3, power:10, defense:10, reach:9, stamina:3, move:'Backboard Breaker', special:'A towering leap into an arena-rattling body slam.', look:{ hairStyle:'bald', beard:'goatee', width:1.34, height:1.22, gear:'bigshoes', mark:'none' } },
  { id:'danish', name:'Danish Rods', title:'The Wild Card', style:'Chaos Defender', color:'#df3d85', accent:'#58e6be', skin:'#7b4a32', hair:'#f0d565', speed:8, power:6, defense:9, reach:7, stamina:9, move:'Rebound Riot', special:'An unpredictable spinning attack that reflects damage.', look:{ hairStyle:'spikes', beard:'none', width:.88, height:1.13, gear:'armbands', mark:'patchwork' } },
  { id:'con', name:'Con McCon', title:'The Double Champ-ish', style:'Southpaw Striker', color:'#256846', accent:'#da9833', skin:'#edd0b3', hair:'#b76132', speed:9, power:8, defense:5, reach:7, stamina:7, move:'Emerald Left', special:'A perfectly timed straight left with massive stun.', look:{ hairStyle:'sweptback', beard:'full', width:1.02, height:1.01, gear:'fightgloves', mark:'chest' } },
  { id:'letsnot', name:'Let’s Not', title:'The Beast-ish', style:'Wrestling Tank', color:'#28272b', accent:'#d33127', skin:'#e1b18c', hair:'#d3be8f', speed:4, power:10, defense:9, reach:7, stamina:6, move:'Avoid This', special:'A chain of takedowns ending in a thunderous suplex.', look:{ hairStyle:'blondcrew', beard:'stubble', width:1.29, height:1.08, gear:'fightgloves', mark:'back' } },
  { id:'beib', name:'Beib Medoff', title:'The Mountain Eagle', style:'Chain Grappler', color:'#2d3430', accent:'#d8c6a1', skin:'#d6a077', hair:'#201711', speed:7, power:8, defense:10, reach:6, stamina:10, move:'Eagle Lock', special:'A relentless takedown chain finished by a crushing ground slam.', look:{ hairStyle:'shortcurl', beard:'full', width:1.08, height:1.02, gear:'fightgloves', mark:'none' } },
  { id:'warrior', name:'The Warrior', title:'The Neon Tempest', style:'Explosive Powerhouse', color:'#ef4d9b', accent:'#35d9ed', skin:'#d59a72', hair:'#6d2b24', speed:8, power:9, defense:6, reach:7, stamina:8, move:'Final Charge', special:'A roaring sprint that ends in a devastating flying shoulder strike.', look:{ hairStyle:'mane', beard:'none', width:1.14, height:1.08, gear:'armbands', mark:'none', accessory:'mask' } },
  { id:'kayess', name:'Kayess Hi', title:'The Crossover', style:'Hybrid Boxer', color:'#38205d', accent:'#e2b648', skin:'#75462f', hair:'#171211', speed:8, power:7, defense:6, reach:7, stamina:8, move:'Overload Right', special:'A burst-step overhand that lands with a crackling second impact.', look:{ hairStyle:'twists', beard:'trim', width:1.01, height:1.04, gear:'gloves', mark:'none', accessory:'bandana' } }
];

export const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

export function attackDamage(fighter, kind, blocking = false) {
  const base = kind === 'light' ? 4.4 : kind === 'heavy' ? 8.5 : 16;
  const scaled = base * (0.72 + fighter.power * 0.045);
  return Number((blocking ? scaled * 0.24 : scaled).toFixed(2));
}

export function selectCpu(playerId, random = Math.random) {
  const choices = ROSTER.filter(f => f.id !== playerId);
  return choices[Math.floor(random() * choices.length)];
}
